[tool.poetry]
name = "pyqt5"
version = "0.1.0"
description = ""
authors = ["n.vladimirov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
